---
- name: PGSQL | configure | debian.
  become: true
  become_user: "{{ postgresql_user }}" 
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: 0600
    backup: true
  with_items:
    - {src: '../templates/pg_hba.conf.j2',dest: '/etc/postgresql/12/main/pg_hba.conf'}
    - {src: '../templates/postgresql.conf.j2',dest: '/etc/postgresql/12/main/postgresql.conf'}
  notify: debian | Restart PGSQL
  when: postgresql_conf_state and ansible_os_family == 'Debian'

- name: PGSQL | configure | centos.
  become: true
  become_user: "{{ postgresql_user }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: 0600
    backup: true
  with_items:
    - {src: '../templates/pg_hba.conf.j2',dest: '/var/lib/pgsql/12/data/pg_hba.conf'}
    - {src: '../templates/postgresql.conf.j2',dest: '/var/lib/pgsql/12/data/postgresql.conf'}
  notify: centos | Restart PGSQL
  when: ansible_distribution == 'CentOS'

- name: PGSQL | trigger start service.
  become: true
  service:
    name: "{{ postgresql_service_name }}-{{ postgresql_version }}.service"
    state: started
  when: ansible_distribution == 'CentOS'

- name: PGSQL | Set postgres password
  postgresql_user: name={{ postgresql_user }} password=postgres
  become: true
  become_user: "{{ postgresql_user }}"