---
- name: PGSQL | install gpg | apt
  become: true
  apt:
    update_cache: yes
    name: 
      - "gpg"
      - "sudo"
    state: present

- name: PGSQL | add key | apt
  become: true
  apt_key:
    url: "{{ postgresql_apt_key }}"
    state: present

- name: PGSQL | add repository | apt
  become: true
  apt_repository:
    repo: "{{ postgresql_apt_repository }}"
    state: present

- name: PGSQL | install packages | apt
  become: true
  apt: 
    update_cache: yes
    name: "{{ postgresql_debian_packages }}"
    state: present