---
- name: debian | Restart PGSQL
  become: true
  service:
    name: "{{ postgresql_service_name }}.service"
    state: restarted
  when: ansible_os_family == 'Debian'

- name: centos | Restart PGSQL
  become: true
  service:
    name: "{{ postgresql_service_name }}-{{ postgresql_version }}.service"
    state: restarted
  when: ansible_distribution == 'CentOS'